
image: ruby:3.2

stages:
  - test
  - build

before_script:
  - ruby --version
  - gem install rspec pdf-reader docx

test:
  stage: test
  script:
    - rspec test/spec.rb 

build:
  stage: build
  script:
    - gem build telegem.gemspec
  artifacts:
    paths:
      - telegem-*.gem
  only:
    - tags